let data = [
  { "id":"1",
    "title":"What Are Your Demands: 1",
    "cost": "0",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"+2",
    "smallSuccessConversationPoints":"+1",
    "failureConversationPoints":"0",
    "bigSuccessThreatChange":"0",
    "smallSuccessThreatChange":"0",
    "failureThreatChange":"+1",
    "bigSuccessRevealDemand":"true",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"0",
    "smallSuccessHostageRelease":"0",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"0",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"false",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
  },
  { "id":"2",
    "title":"What Are Your Demands: 2",
    "cost": "0",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"+2",
    "smallSuccessConversationPoints":"+1",
    "failureConversationPoints":"0",
    "bigSuccessThreatChange":"0",
    "smallSuccessThreatChange":"0",
    "failureThreatChange":"+1",
    "bigSuccessRevealDemand":"true",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"0",
    "smallSuccessHostageRelease":"0",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"0",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"false",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
  },
  { "id":"3",
    "title":"Small Talk: 1",
    "cost": "0",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"+3",
    "smallSuccessConversationPoints":"+2",
    "failureConversationPoints":"+1",
    "bigSuccessThreatChange":"0",
    "smallSuccessThreatChange":"0",
    "failureThreatChange":"+1",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"0",
    "smallSuccessHostageRelease":"0",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"0",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"true",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
  },
  { "id":"4",
    "title":"Small Talk: 2",
    "cost": "0",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"+3",
    "smallSuccessConversationPoints":"+2",
    "failureConversationPoints":"+1",
    "bigSuccessThreatChange":"0",
    "smallSuccessThreatChange":"0",
    "failureThreatChange":"+1",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"0",
    "smallSuccessHostageRelease":"0",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"0",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"true",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
  },
  { "id":"5",
    "title":"Keep Cool: 1",
    "cost": "0",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"+1",
    "smallSuccessConversationPoints":"0",
    "failureConversationPoints":"-1",
    "bigSuccessThreatChange":"-1",
    "smallSuccessThreatChange":"-1",
    "failureThreatChange":"0",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"0",
    "smallSuccessHostageRelease":"0",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"0",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"false",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
  },
  { "id":"6",
    "title":"Keep Cool: 2",
    "cost": "0",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"+1",
    "smallSuccessConversationPoints":"0",
    "failureConversationPoints":"-1",
    "bigSuccessThreatChange":"-1",
    "smallSuccessThreatChange":"-1",
    "failureThreatChange":"0",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"0",
    "smallSuccessHostageRelease":"0",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"0",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"false",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
  },
  { "id":"7",
    "title":"Just A Few Minutes More: 1",
    "cost": "2",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"+4",
    "smallSuccessConversationPoints":"+3",
    "failureConversationPoints":"0",
    "bigSuccessThreatChange":"0",
    "smallSuccessThreatChange":"+1",
    "failureThreatChange":"+2",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"0",
    "smallSuccessHostageRelease":"0",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"0",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"true",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
  },
  { "id":"8",
    "title":"Just A Few Minutes More: 2",
    "cost": "2",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"+4",
    "smallSuccessConversationPoints":"+3",
    "failureConversationPoints":"0",
    "bigSuccessThreatChange":"0",
    "smallSuccessThreatChange":"+1",
    "failureThreatChange":"+2",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"0",
    "smallSuccessHostageRelease":"0",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"0",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"true",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
    },
  { "id":"9",
    "title":"You Need To Trust Me: 1",
    "cost": "2",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"0",
    "smallSuccessConversationPoints":"+1",
    "failureConversationPoints":"+1",
    "bigSuccessThreatChange":"0",
    "smallSuccessThreatChange":"0",
    "failureThreatChange":"+1",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"0",
    "smallSuccessHostageRelease":"0",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"0",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"false",
    "bigSuccess4to5": "true",
    "smallSuccess4to5": "false"
    },
  { "id":"10",
    "title":"You Need To Trust Me: 2",
    "cost": "2",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"0",
    "smallSuccessConversationPoints":"+1",
    "failureConversationPoints":"+1",
    "bigSuccessThreatChange":"0",
    "smallSuccessThreatChange":"0",
    "failureThreatChange":"+1",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"0",
    "smallSuccessHostageRelease":"0",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"0",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"false",
    "bigSuccess4to5": "true",
    "smallSuccess4to5": "false"
    },
{ "id":"11",
    "title":"Just Stay Calm: 1",
    "cost": "2",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"0",
    "smallSuccessConversationPoints":"0",
    "failureConversationPoints":"0",
    "bigSuccessThreatChange":"-2",
    "smallSuccessThreatChange":"-1",
    "failureThreatChange":"+1",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"0",
    "smallSuccessHostageRelease":"0",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"0",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"true",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
    },
  { "id":"12",
    "title":"Just Stay Calm: 2",
    "cost": "2",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"0",
    "smallSuccessConversationPoints":"0",
    "failureConversationPoints":"0",
    "bigSuccessThreatChange":"-2",
    "smallSuccessThreatChange":"-1",
    "failureThreatChange":"+1",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"0",
    "smallSuccessHostageRelease":"0",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"0",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"true",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
  },
  { "id":"13",
    "title":"Minor Extraction: 1",
    "cost": "3",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"0",
    "smallSuccessConversationPoints":"0",
    "failureConversationPoints":"0",
    "bigSuccessThreatChange":"0",
    "smallSuccessThreatChange":"+1",
    "failureThreatChange":"0",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"2",
    "smallSuccessHostageRelease":"1",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"1",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"true",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
    },
  { "id":"14",
    "title":"Minor Extraction: 2",
    "cost": "3",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"0",
    "smallSuccessConversationPoints":"0",
    "failureConversationPoints":"0",
    "bigSuccessThreatChange":"0",
    "smallSuccessThreatChange":"+1",
    "failureThreatChange":"0",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"2",
    "smallSuccessHostageRelease":"1",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"1",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"true",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
    },
  { "id":"15",
    "title":"A Bold Lie",
    "cost": "4",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"+1",
    "smallSuccessConversationPoints":"+1",
    "failureConversationPoints":"0",
    "bigSuccessThreatChange":"-3",
    "smallSuccessThreatChange":"-1",
    "failureThreatChange":"+3",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"0",
    "smallSuccessHostageRelease":"0",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"0",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"false",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
    },
  { "id":"16",
    "title":"An Empty Promise",
    "cost": "4",
    "bigSuccessDice":"+2",
    "smallSuccessDice":"+2",
    "failureDice":"-1",
    "bigSuccessConversationPoints":"+2",
    "smallSuccessConversationPoints":"0",
    "failureConversationPoints":"0",
    "bigSuccessThreatChange":"0",
    "smallSuccessThreatChange":"0",
    "failureThreatChange":"0",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"0",
    "smallSuccessHostageRelease":"0",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"1",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"false",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
    },
  { "id":"17",
    "title":"I'm Coming In To Talk",
    "cost": "5",
    "bigSuccessDice":"+2",
    "smallSuccessDice":"+1",
    "failureDice":"0",
    "bigSuccessConversationPoints":"0",
    "smallSuccessConversationPoints":"0",
    "failureConversationPoints":"0",
    "bigSuccessThreatChange":"0",
    "smallSuccessThreatChange":"0",
    "failureThreatChange":"0",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"true",
    "bigSuccessHostageRelease":"0",
    "smallSuccessHostageRelease":"0",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"0",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"false",
    "smallSuccessConversationEnd":"false",
    "failureConversationEnd":"false",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
    },
  { "id":"18",
    "title":"Major Extraction",
    "cost": "6",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"0",
    "smallSuccessConversationPoints":"0",
    "failureConversationPoints":"0",
    "bigSuccessThreatChange":"2",
    "smallSuccessThreatChange":"2",
    "failureThreatChange":"2",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"3",
    "smallSuccessHostageRelease":"2",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"2",
    "bigSuccessAbductorKill":"false",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"true",
    "smallSuccessConversationEnd":"true",
    "failureConversationEnd":"true",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
    },
  { "id":"19",
    "title":"Sniper, Take The Shot",
    "cost": "7",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"0",
    "smallSuccessConversationPoints":"0",
    "failureConversationPoints":"0",
    "bigSuccessThreatChange":"0",
    "smallSuccessThreatChange":"0",
    "failureThreatChange":"+2",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"true",
    "bigSuccessHostageRelease":"2",
    "smallSuccessHostageRelease":"0",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"2",
    "bigSuccessAbductorKill":"true",
    "smallSuccessAbductorKill":"true",
    "failureAbductorEscape":"false",
    "bigSuccessConversationEnd":"true",
    "smallSuccessConversationEnd":"true",
    "failureConversationEnd":"true",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
    },
  { "id":"20",
    "title":"All Units, Get In There, NOW!",
    "cost": "8",
    "bigSuccessDice":"0",
    "smallSuccessDice":"0",
    "failureDice":"0",
    "bigSuccessConversationPoints":"0",
    "smallSuccessConversationPoints":"0",
    "failureConversationPoints":"0",
    "bigSuccessThreatChange":"0",
    "smallSuccessThreatChange":"3",
    "failureThreatChange":"0",
    "bigSuccessRevealDemand":"false",
    "smallSuccessRevealDemand":"false",
    "failureCardRemove":"false",
    "bigSuccessHostageRelease":"4",
    "smallSuccessHostageRelease":"3",
    "smallSuccessHostageKill":"0",
    "failureHostageKill":"0",
    "bigSuccessAbductorKill":"true",
    "smallSuccessAbductorKill":"false",
    "failureAbductorEscape":"true",
    "bigSuccessConversationEnd":"true",
    "smallSuccessConversationEnd":"true",
    "failureConversationEnd":"true",
    "bigSuccess4to5": "false",
    "smallSuccess4to5": "false"
    },
]

let hostagetaker = [
  {
    'name': 'Ann Greashopper', 'description': 'After being unable to return her defective toaster, Ann seems to have lost it completely and returned to hold the shop owner and his wife hostage.  <br><br>Time for you to do your thing, Cap!'
  },
  {
    'name': 'Arkayne Massua', 'description': 'A member of a radical cell, Arkayne was none too pleased when we arrested the rest of his group.  He\'s now taken some of our diplomats hostage as leverage to get what he wants.<br><br> I don\'t envy you this one, Cap!'
  }
]
